name: terraform-destroy

on:

  workflow_dispatch:


jobs:
  build:
    name: Terraform CICD Server 
    env: 
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_LINUX_PASSWORD: ${{ secrets.LINUX_PASSWORD }}
    runs-on: ubuntu-latest

    steps:      
      - name: Git Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Terraform SetUp
        id: setup
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Destroy
        id: destroy
        run: terraform apply -destroy -auto-approve